### ISSUE TITLE
About the use of C++

### ISSUE THREAD

**Issue by Raj2032** [hugoam/toy#10]
This site mentions that I am able to directly code in C++. Does that mean that the game engine has to be recompiled each time I am programming in C++?

**Comment by hugoam** [comment]
Please do not use github issues for this kind of general questions :)
Feel free to reach me directly, join the gitter room, or the discourse.
Regarding your question, the engine doesn't have to be recompiled, as long as you don't touch the engine code. The game itself, coded in C++, will have to be recompiled as soon as you change its code.
