### ISSUE TITLE
Build system issues  ("genie" / cmake / gmake)

### ISSUE THREAD

**Issue by tcShadowWalker** [hugoam/toy#2]
Toy sounds like a really interesting project to look into.

Unfortunately, i'm unable to build the project.
Neither the cmake nor the gmake generators work.

1. Calling the 'genie' script from outside the project directory (out-of-source build) does not seem to work. Nothing is generated.
2. The CMake files use non-standard conventions:
```
$ cmake .
-- The C compiler identification is Clang 6.0.1
-- The CXX compiler identification is Clang 6.0.1
-- Check for working C compiler: /usr/bin/clang
-- Check for working C compiler: /usr/bin/clang -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/clang++
-- Check for working CXX compiler: /usr/bin/clang++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: /home/dev/Development/toy/build/projects/cmake
[build@XXX  /home/dev/Development/toy/build/projects/cmake ]$ make
[build@XXX  /home/dev/Development/toy/build/projects/cmake ]$ 
```
Nothing happens, because CMAKE_BUILD_TYPE Must be set to either 'Release' or 'Debug'. The cmake default, however, is RELWITHDEBINFO. 
Unfortunately, the generated CMake files contain custom conditionals like these:
```
if(CMAKE_BUILD_TYPE MATCHES "Debug")
  add_library(toy_d SHARED ${source_list})
endif()

if(CMAKE_BUILD_TYPE MATCHES "Release")
  add_library(toy SHARED ${source_list})
endif()
```
3. Unfortunately, it still doesn't work:
```
[build@XXX  /home/dev/Development/toy/build/projects/cmake ]$ cmake . -DCMAKE_BUILD_TYPE=Debug
-- Configuring done
CMake Error at json11/CMakeLists.txt:35 (add_library):
  Cannot find source file:
    ../../../../mud/3rdparty/json11/json11.h
  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
  .hpp .hxx .in .txx
CMake Error at json11/CMakeLists.txt:35 (add_library):
  No SOURCES given to target: json11_d
-- Build files have been written to: /home/dev/Development/toy/build/projects/cmake
```
4. The gmake generator does not work either:
Generating the makefiles works, however, Compilation fails with lots of these errors:
`/usr/include/gnu/stubs.h:7:11: fatal error: 'gnu/stubs-32.h' file not found`
I 'think' it tried to compile for a 32bit platform.
5. Setting the platform to 64 bit doesn't work either:
```
[build@XXX  /home/dev/Development/toy ]$ ./bin/linux/genie --os=linux --gcc=linux-clang --platform=x64 gmake
lib mud
    links shaderc
    links bimg_decode
    links vg
    links bgfx
    links bimg
    links bx
    links glfw
    links lua
    links stb_rect_pack
    links json11
lib toy
    links mud
    links vg
    links bimg_decode
    links glfw
    links shaderc
    links bgfx
    links bimg
    links bx
    links lua
    links stb_rect_pack
    links json11
lib editor
    links toy
lib _05_character
    links toy
lib ex_minimal
    links toy
lib ex_space
    links toy
lib ex_platform
    links toy
lib ex_blocks
    links toy
Error: toy does not target native platform
Native platform settings are required for the --platform feature.
stack traceback:
        [C]: in function 'error'
        [string "_WORKING_DIR        = os.getcwd()..."]:65: in function '_premake_main'
```
Of course, this is a normal x86-64 (Arch-)Linux:
> $ uname -a
> Linux XXX 4.17.10-1-ARCH #1 SMP PREEMPT Wed Jul 25 11:23:00 UTC 2018 x86_64 GNU/Linux

I think it would be nice if toy used a normal build system like CMake in a standard, idiomatic way.

**Comment by hugoam** [comment]
Hi !
- When calling genie, it looks for a `scripts/genie.lua` file in the current directory, so if you want to do an outside of source build, you would have to have a `genie.lua` file in that relative folder. Maybe genie has an option to specify the path of the lua file, but I'm not sure (must ask the owner)
- CMake is not really officially supported by genie. I never tried it. I heard there is an external project somewhere that implemented a generator, but not sure what it's worth
- I wouldn't mind if someone contributes a CMake build system for toy, but I won't have time to implement one myself before a good while
- The platform and os need not be specified when calling `genie.lua`, so you should actually call : 
`./bin/linux/genie --gcc=linux-clang gmake` (linux os should be detected as well). After that, the target config is actually specified by calling `make config=debug64` for a 64 bit build

**Comment by tcShadowWalker** [comment]
Thanks for the response. That actually did the trick!
