### ISSUE TITLE
cannot open toolchain.lua - cant generate build

### ISSUE THREAD

**Issue by Vawx** [hugoam/toy#5]
cloned down, cd to toy/bin/windows.

./genie vs2015

get following:

./genie vs2015
cannot open c:/Users/altck/Desktop/Toy/toy/mud/scripts/toolchain.lua: No such file or directory
stack traceback:
        [C]: in upvalue 'builtin_dofile'
        [string "premake = { }..."]:103: in function 'dofile'
        c:/Users/altck/Desktop/Toy/toy/scripts/toolchain.lua:9: in main chunk
        [C]: in upvalue 'builtin_dofile'
        [string "premake = { }..."]:103: in function 'dofile'
        c:/Users/altck/Desktop/Toy/toy/scripts/genie.lua:20: in main chunk
        [C]: in upvalue 'builtin_dofile'
        [string "premake = { }..."]:103: in function 'dofile'
        [string "_WORKING_DIR        = os.getcwd()..."]:45: in function '_premake_main'

**Comment by hugoam** [comment]
Hey, genie must be called from the root project directory you want to build, so in your case, you must call it from `toy/` : `bin\windows\genie vs2015`

**Comment by Vawx** [comment]
hey, tried that too:

![image](https://user-images.githubusercontent.com/4406322/43592900-8bbb09d6-9644-11e8-90cd-8f9af399edc1.png)

**Comment by hugoam** [comment]
I think your mud folder might be empty :) You either need to clone with `--recursive`, or you need to do `git submodule update --init` (first in toy, and then once more in toy/mud)

**Comment by Vawx** [comment]
Totally missed the --recursive.

Thank you for your patience and help.
