### ISSUE TITLE
Function signature mismatch

### ISSUE THREAD

**Issue by anshul-soni** [hugoam/toy#7]
Function signature in 

> example\05_character\05_character.cpp

> jams\blocks\ex_blocks.cpp

> jams\minimal\ex_minimal.cpp

> jams\platform\ex_platform.cpp

> jams\space\ex_space.cpp

doesnt match the signature of base class virtual function 

`virtual void pump(GameShell& app, Game& game, Widget& ui)`

**Comment by hugoam** [comment]
Some files went out of sync with some of the modifications I did with the engine.
Should be fixed now: https://github.com/hugoam/toy/commit/f6cb4e12bcf34520b87e56f9e00caf4f511daaf3 :)
